document.getElementById("medicalDiagnosis").innerHTML =
  "hdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkf";

document.getElementById("medicinesTaken").innerHTML =
  "hdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhdskfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkfhsdjkhsdjkfhsdjkhsdjkfhsdjkfhsdjkfhsdjkfhsdjkf";

function logOut() {
  window.open("Login.html", "_self");
}
